"""
Indonesian Category Classifier — Inference module for Phase 4A-ID.

Loads the saved Indonesian news category sklearn pipeline and exposes predict().

IMPORTANT: The model was trained on LLM-generated labels (not human-annotated).
See model metadata for full details.

Architecture:
    language = "id"  ->  IndonesianCategoryClassifier
    language = "en"  ->  CategoryClassifier (Phase 4A)
"""

import json
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_MODEL_PATH = _BACKEND_DIR / "ml" / "models" / "news_category_id_model.joblib"
_METADATA_PATH = _BACKEND_DIR / "ml" / "models" / "news_category_id_metadata.json"

VALID_CATEGORIES = {
    "BENCANA_LINGKUNGAN",
    "EKONOMI_BISNIS",
    "HUKUM_KRIMINAL",
    "OLAHRAGA",
    "POLITIK_PEMERINTAHAN",
    "TEKNOLOGI_DIGITAL",
}


# ---------------------------------------------------------------------------
# Classifier class
# ---------------------------------------------------------------------------

class IndonesianCategoryClassifier:
    """
    Wrapper around the saved sklearn Pipeline for Indonesian news classification.

    Lazy-loads on first use. Thread-safe for read-only inference.

    Categories:
      - BENCANA_LINGKUNGAN (Disaster & Environment)
      - EKONOMI_BISNIS     (Economy & Business)
      - HUKUM_KRIMINAL     (Law & Crime)
      - OLAHRAGA           (Sports)
      - POLITIK_PEMERINTAHAN (Politics & Government)
      - TEKNOLOGI_DIGITAL  (Technology & Digital)

    IMPORTANT: Labels in training data were generated by LLM (not human-curated).
    See metadata for full details.
    """

    def __init__(self) -> None:
        self._pipeline = None
        self._metadata: dict = {}

    def _load(self) -> None:
        """Load pipeline and metadata from disk."""
        if self._pipeline is not None:
            return

        if not _MODEL_PATH.exists():
            raise FileNotFoundError(
                f"Indonesian Category Model not found: {_MODEL_PATH}\n"
                "Run 'python ml/scripts/train_indonesian_classifier.py' first."
            )

        import joblib
        logger.info("Loading Indonesian category classifier from %s", _MODEL_PATH)
        self._pipeline = joblib.load(_MODEL_PATH)

        if _METADATA_PATH.exists():
            self._metadata = json.loads(_METADATA_PATH.read_text(encoding="utf-8"))
            logger.info(
                "Indonesian model loaded: %s  Accuracy=%.4f  MacroF1=%.4f",
                self._metadata.get("model_name"),
                self._metadata.get("accuracy", 0),
                self._metadata.get("macro_f1", 0),
            )
            if self._metadata.get("label_origin"):
                logger.warning(
                    "Label origin: %s", self._metadata["label_origin"][:100]
                )

    def predict(self, text: str) -> dict:
        """
        Predict the category of an Indonesian news article.

        Args:
            text: Indonesian news text (title + content recommended).

        Returns:
            dict with keys:
                category   (str)   -- predicted category from VALID_CATEGORIES
                confidence (float) -- probability from calibrated classifier [0.0, 1.0]
                all_scores (dict)  -- probability per class
        """
        self._load()

        if not text or not isinstance(text, str):
            raise ValueError("text must be a non-empty string")
        text = text.strip()
        if len(text) < 5:
            raise ValueError("text is too short to classify")

        proba = self._pipeline.predict_proba([text])[0]
        classes = self._pipeline.classes_

        scores = {str(cls): round(float(p), 4) for cls, p in zip(classes, proba)}
        best_idx = int(proba.argmax())
        predicted = str(classes[best_idx])
        confidence = round(float(proba[best_idx]), 4)

        return {
            "category": predicted,
            "confidence": confidence,
            "all_scores": scores,
        }

    def predict_batch(self, texts: list[str]) -> list[dict]:
        """Predict categories for a list of texts."""
        self._load()
        if not texts:
            return []

        proba_matrix = self._pipeline.predict_proba(texts)
        classes = self._pipeline.classes_
        results = []
        for proba in proba_matrix:
            best_idx = int(proba.argmax())
            scores = {str(cls): round(float(p), 4) for cls, p in zip(classes, proba)}
            results.append({
                "category": str(classes[best_idx]),
                "confidence": round(float(proba[best_idx]), 4),
                "all_scores": scores,
            })
        return results

    @property
    def metadata(self) -> dict:
        self._load()
        return dict(self._metadata)

    @property
    def categories(self) -> list[str]:
        self._load()
        return list(self._pipeline.classes_)

    def is_loaded(self) -> bool:
        return self._pipeline is not None


@lru_cache(maxsize=1)
def get_indonesian_classifier() -> IndonesianCategoryClassifier:
    """Module-level singleton lazy loader."""
    return IndonesianCategoryClassifier()
