"""initial_schema_articles_analyses_keywords_entities

Revision ID: 053fe81f27eb
Revises: 
Create Date: 2026-08-14 13:55:44.591075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053fe81f27eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_created_at', 'articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index('ix_articles_url', 'articles', ['url'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True, comment='Estimated reading time in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_article_id'), 'analyses', ['article_id'], unique=False)
    op.create_index('ix_analyses_category', 'analyses', ['category'], unique=False)
    op.create_index('ix_analyses_created_at', 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index('ix_analyses_sentiment', 'analyses', ['sentiment'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=500), nullable=False, comment='The recognized entity text'),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment='E.g. PERSON, ORGANIZATION, LOCATION, COUNTRY, COMPANY'),
    sa.Column('score', sa.Float(), nullable=True, comment='NER confidence score'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_analysis_id'), 'entities', ['analysis_id'], unique=False)
    op.create_index('ix_entities_entity', 'entities', ['entity'], unique=False)
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=True, comment='Relevance score from NLP model'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_analysis_id'), 'keywords', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index('ix_keywords_keyword', 'keywords', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_keywords_keyword', table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_analysis_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_index('ix_entities_entity', table_name='entities')
    op.drop_index(op.f('ix_entities_analysis_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_analyses_sentiment', table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index('ix_analyses_created_at', table_name='analyses')
    op.drop_index('ix_analyses_category', table_name='analyses')
    op.drop_index(op.f('ix_analyses_article_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_articles_url', table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index('ix_articles_created_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
