"""add_author_word_count_reading_time_unique_url_to_articles

Revision ID: 1df957b08fb3
Revises: 053fe81f27eb
Create Date: 2026-08-14 14:03:32.170385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df957b08fb3'
down_revision: Union[str, Sequence[str], None] = '053fe81f27eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('reading_time', sa.Integer(), nullable=True, comment='Estimated reading time in minutes'))
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_unique_constraint('uq_articles_url', 'articles', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_articles_url', 'articles', type_='unique')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    op.drop_column('articles', 'reading_time')
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###
