"""Phase 5A: Analysis Database and Persistence

Revision ID: 2c8252625a87
Revises: 1df957b08fb3
Create Date: 2026-08-14 16:09:23.293477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c8252625a87'
down_revision: Union[str, Sequence[str], None] = '1df957b08fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False, comment='The recognized entity text'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='E.g. PERSON, ORGANIZATION, LOCATION'),
    sa.Column('start_position', sa.Integer(), nullable=False, comment='Character start offset in text'),
    sa.Column('end_position', sa.Integer(), nullable=False, comment='Character end offset in text'),
    sa.Column('score', sa.Float(), nullable=True, comment='NER confidence score'),
    sa.Column('normalized_label', sa.String(length=100), nullable=True, comment='Normalized/mapped label if any'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_entities_analysis_id'), 'analysis_entities', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_entities_id'), 'analysis_entities', ['id'], unique=False)
    op.create_index('ix_analysis_entities_label', 'analysis_entities', ['label'], unique=False)
    op.create_index('ix_analysis_entities_text', 'analysis_entities', ['text'], unique=False)
    op.create_table('analysis_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=True, comment='Relevance score from NLP model'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='Ranking position (1 is best)'),
    sa.Column('method', sa.String(length=50), nullable=True, comment='Method used for extraction (e.g. yake)'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'keyword', name='uq_analysis_keywords_analysis_id_keyword')
    )
    op.create_index(op.f('ix_analysis_keywords_analysis_id'), 'analysis_keywords', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_keywords_id'), 'analysis_keywords', ['id'], unique=False)
    op.create_index('ix_analysis_keywords_keyword', 'analysis_keywords', ['keyword'], unique=False)
    op.drop_index(op.f('ix_entities_analysis_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_keywords_analysis_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    op.add_column('analyses', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.add_column('analyses', sa.Column('language_name', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('language_confidence', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('category_confidence', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('sentiment_confidence', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_analyses_language_code'), 'analyses', ['language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_language_code'), table_name='analyses')
    op.drop_column('analyses', 'updated_at')
    op.drop_column('analyses', 'model_versions')
    op.drop_column('analyses', 'sentiment_confidence')
    op.drop_column('analyses', 'category_confidence')
    op.drop_column('analyses', 'language_confidence')
    op.drop_column('analyses', 'language_name')
    op.drop_column('analyses', 'language_code')
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Relevance score from NLP model'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('keywords_analysis_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('keywords_pkey'))
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_analysis_id'), 'keywords', ['analysis_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='The recognized entity text'),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='E.g. PERSON, ORGANIZATION, LOCATION, COUNTRY, COMPANY'),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='NER confidence score'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('entities_analysis_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('entities_pkey'))
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_entity'), 'entities', ['entity'], unique=False)
    op.create_index(op.f('ix_entities_analysis_id'), 'entities', ['analysis_id'], unique=False)
    op.drop_index('ix_analysis_keywords_keyword', table_name='analysis_keywords')
    op.drop_index(op.f('ix_analysis_keywords_id'), table_name='analysis_keywords')
    op.drop_index(op.f('ix_analysis_keywords_analysis_id'), table_name='analysis_keywords')
    op.drop_table('analysis_keywords')
    op.drop_index('ix_analysis_entities_text', table_name='analysis_entities')
    op.drop_index('ix_analysis_entities_label', table_name='analysis_entities')
    op.drop_index(op.f('ix_analysis_entities_id'), table_name='analysis_entities')
    op.drop_index(op.f('ix_analysis_entities_analysis_id'), table_name='analysis_entities')
    op.drop_table('analysis_entities')
    # ### end Alembic commands ###
