"""add_clickbait_score

Revision ID: 55b91e516ea1
Revises: 2c8252625a87
Create Date: 2026-08-15 01:41:08.407574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b91e516ea1'
down_revision: Union[str, Sequence[str], None] = '2c8252625a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('clickbait_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'clickbait_score')
    # ### end Alembic commands ###
