"""Add objectivity fields to analysis

Revision ID: ede9f276c7ad
Revises: 55b91e516ea1
Create Date: 2026-08-19 21:01:45.591702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ede9f276c7ad'
down_revision: Union[str, Sequence[str], None] = '55b91e516ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('objectivity_score', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('objectivity_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'objectivity_details')
    op.drop_column('analyses', 'objectivity_score')
    # ### end Alembic commands ###
