"""
Preprocessing module for Indonesian News Category dataset.

Dataset: fahadh4ilyas/indonesian_news_datasets
Source : Hugging Face Hub
License: CC-BY-NC-4.0

Label origin: AUTOMATICALLY GENERATED by LLM (Qwen3-30B-A3B-Instruct-2507-FP8)
              Labels have NOT been human-curated. Use results with awareness of this limitation.

Categories:
  POLITIK_PEMERINTAHAN (Politics)
  EKONOMI_BISNIS       (Economy & Business)
  HUKUM_KRIMINAL       (Law & Crime)
  OLAHRAGA             (Sports)
  TEKNOLOGI_DIGITAL    (Technology)
  BENCANA_LINGKUNGAN   (Disaster & Environment)

Text strategy: title + " " + content (first 2000 chars of content to avoid noise)

Usage:
    from ml.scripts.indonesian_preprocess import load_and_clean
"""

import re
import sys
import unicodedata
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

RANDOM_STATE = 42

DATASET_ID = "fahadh4ilyas/indonesian_news_datasets"
DATASET_SOURCE = "Hugging Face Hub"
DATASET_LICENSE = "CC-BY-NC-4.0"
LABEL_ORIGIN = (
    "AUTOMATICALLY GENERATED by LLM (Qwen/Qwen3-30B-A3B-Instruct-2507-FP8). "
    "Labels have NOT been human-curated."
)

CATEGORIES = [
    "BENCANA_LINGKUNGAN",
    "EKONOMI_BISNIS",
    "HUKUM_KRIMINAL",
    "OLAHRAGA",
    "POLITIK_PEMERINTAHAN",
    "TEKNOLOGI_DIGITAL",
]

TEXT_COLUMN = "text"
LABEL_COLUMN = "label"

# Limit content length to avoid noise from very long articles
CONTENT_MAX_CHARS = 2000


# ---------------------------------------------------------------------------
# Text cleaning — minimal, preserve Indonesian context
# ---------------------------------------------------------------------------

def clean_text(text: str) -> str:
    """
    Minimal cleaning for Indonesian news text.
    
    Preserves:
    - Original words (no stemming)
    - Negation words: tidak, bukan, belum, tanpa, jangan
    - Proper nouns, entity names
    
    Removes:
    - HTML tags and entities
    - Malformed Unicode control chars
    - Redundant whitespace / empty lines
    - Leading/trailing whitespace
    """
    if not isinstance(text, str):
        text = str(text) if text is not None else ""

    # Unicode NFC normalization
    text = unicodedata.normalize("NFC", text)

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove HTML entities
    text = re.sub(r"&[a-zA-Z]+;", " ", text)
    text = re.sub(r"&#\d+;", " ", text)
    text = re.sub(r"&amp;", " ", text)

    # Remove Unicode control characters (except newline/tab)
    text = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", " ", text)

    # Normalize whitespace
    text = re.sub(r"\r\n|\r", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()


def build_text_field(row: pd.Series) -> str:
    """
    Combine title + content into single text field.
    
    Strategy: title + " " + first CONTENT_MAX_CHARS characters of content
    Rationale:
    - Title alone loses context
    - Full content can be very noisy (ads, navigation text, boilerplate)
    - Limiting to CONTENT_MAX_CHARS balances information vs. noise
    """
    title = str(row.get("title", "") or "").strip()
    content = str(row.get("content", "") or "").strip()

    # Limit content to reduce noise
    if len(content) > CONTENT_MAX_CHARS:
        content = content[:CONTENT_MAX_CHARS]

    combined = f"{title} {content}".strip()
    return combined


# ---------------------------------------------------------------------------
# Load & clean
# ---------------------------------------------------------------------------

def load_indonesian_raw() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Download and return (train_raw, test_raw) DataFrames from Hugging Face.
    
    The dataset has native train/test splits — we use them to avoid leakage.
    """
    from datasets import load_dataset
    print(f"Downloading: {DATASET_ID} ...")
    ds = load_dataset(DATASET_ID)
    train_df = ds["train"].to_pandas()
    test_df = ds["test"].to_pandas()
    print(f"  Raw train rows: {len(train_df):,}")
    print(f"  Raw test rows : {len(test_df):,}")
    return train_df, test_df


def preprocess_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Full preprocessing pipeline for the Indonesian dataset.
    
    Steps:
    1. Build combined text (title + content)
    2. Clean text
    3. Drop rows with missing/invalid labels
    4. Drop rows with empty text after cleaning
    5. Remove exact duplicate texts
    
    Returns: DataFrame with columns [TEXT_COLUMN, LABEL_COLUMN]
    """
    df = df.copy()

    # 1. Build combined text
    print("  Building title + content text field...")
    df[TEXT_COLUMN] = df.apply(build_text_field, axis=1)

    # 2. Clean text
    print("  Cleaning text...")
    df[TEXT_COLUMN] = df[TEXT_COLUMN].apply(clean_text)

    # 3. Drop missing/invalid labels
    valid_cats = set(CATEGORIES)
    before = len(df)
    df = df.dropna(subset=[LABEL_COLUMN])
    df = df[df[LABEL_COLUMN].isin(valid_cats)]
    if len(df) < before:
        print(f"  Dropped {before - len(df):,} rows with invalid/missing labels")

    # 4. Drop empty texts
    before = len(df)
    df = df[df[TEXT_COLUMN].str.len() >= 10]
    if len(df) < before:
        print(f"  Dropped {before - len(df):,} rows with too-short text")

    # 5. Remove exact duplicate texts (case-sensitive)
    before = len(df)
    df = df.drop_duplicates(subset=[TEXT_COLUMN])
    if len(df) < before:
        print(f"  Dropped {before - len(df):,} exact duplicate texts")

    df = df.reset_index(drop=True)
    return df[[TEXT_COLUMN, LABEL_COLUMN]]


def load_and_clean() -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Full pipeline: download -> preprocess.
    Returns (train_df, test_df), each with columns [text, label].
    Uses the dataset's native train/test split to prevent leakage.
    """
    train_raw, test_raw = load_indonesian_raw()
    print("Preprocessing train split...")
    train_df = preprocess_df(train_raw)
    print(f"  Final train rows: {len(train_df):,}")

    print("Preprocessing test split...")
    test_df = preprocess_df(test_raw)
    print(f"  Final test rows : {len(test_df):,}")

    print(f"\nClass distribution (train):")
    print(train_df[LABEL_COLUMN].value_counts().to_string())
    return train_df, test_df


if __name__ == "__main__":
    train_df, test_df = load_and_clean()
    print(f"\nSample texts:")
    for _, row in train_df.head(3).iterrows():
        print(f"  [{row[LABEL_COLUMN]}] {row[TEXT_COLUMN][:100]}...")
